apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}
  namespace: default
  labels:
    app: {{.Values.name}}
spec:
  ports:
  - port: 80
    protocol: TCP
    name: flask
  selector:
    app: {{.Values.name}}
    tier: frontend
  type: NodePort